name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["Build N Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker pull $DOCKER_USER/studentperf_api:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f studentperf_api-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker run -it -d -p 80:5000 --name studentperf_api-container $DOCKER_USER/studentperf_api:latest
