# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Runner Cache
        run: rm -rf ~/.npm ~/.cache ~/.pip
        
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Train and save pipeline
        run: python -m src.pipeline.train_pipeline
      
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: artifacts/*.pkl
  
  push-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the Docker image for FastAPI app
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/studentPerf_api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/studentPerf_api:latest